### PR TITLE
Create tabView.js

### PR DESCRIPTION
**Pull request by jams2018**
tabView, top material navigation, a register button as well as the related titles.

### CODE REVIEW

**Comment by mrvirus9898** [comment]
Conflict detected with "react-navigation": "^2.18.2". Do we need to use 2.18.2? or could we get away with 2.18.0? If we do need to use 2.18.2, thats okay, just let us know so we can update in case we don't have all the dependencies.

**Comment by jams2018** [comment]
the correct file should be Activities.js.

**Comment by mrvirus9898** [comment]
Ok, Zach what do you think?

**Comment by zach-daniels** [comment]
It looks like Anar pushed the Activities.js to the main repo, so this pull request is redundant. Try not to push it next time, Anar.

**Pull request closed without merging**
